name: deploy-frontend

on:
  push:
    branches: ["master"]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo 'Construyendo imagen Frontend...'
      - run: docker build -t ${{ secrets.DOCKER_USER }}/frontend-restapi:${{ github.sha }} .
      - run: docker images

      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: docker push
        run: docker push ${{ secrets.DOCKER_USER }}/frontend-restapi:${{ github.sha }}
